/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.main;

import javax.swing.JOptionPane;
import java.awt.CardLayout;
import model.Business.Business;
import model.UserAccountManagement.UserAccount;

/**
 *
 * @author prasa
 */
public class LoginScreen extends javax.swing.JPanel {

    private MainJFrame mainJFrame;
    private Business business;

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen(MainJFrame mainJFrame, Business business) {
        this.mainJFrame = mainJFrame;
        this.business = business;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRole = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 204));

        lblRole.setText("Select a Role:");

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Marketing", "Sales", "Customer" }));

        lblUsername.setText("Username:");

        lblPassword.setText("Password:");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogin)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUsername)
                            .addComponent(lblRole)
                            .addComponent(lblPassword))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername)
                            .addComponent(cmbRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRole))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnLogin)
                .addContainerGap(192, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // Authentication
        if (txtUsername.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input your username.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        UserAccount userAccount = business.getUserAccountDirectory().getUserAccount(txtUsername.getText());
        if (userAccount == null) {
            JOptionPane.showMessageDialog(this, "User not found.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String role = userAccount.getProfile().getRole();
        if (!role.equals(cmbRole.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(this, "User not found.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (txtPassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input your password.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        userAccount = business.getUserAccountDirectory().authenticateUser(txtUsername.getText(), txtPassword.getText());
        if (userAccount == null) {
            JOptionPane.showMessageDialog(this, "Invalid password.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        txtUsername.setText("");
        txtPassword.setText("");
        // Login
        if ("Admin".equals(role)) {
            ui.admin.WorkArea workArea = new ui.admin.WorkArea(mainJFrame.getContentPane(), business, userAccount);
            mainJFrame.getContentPane().add("AdminWorkArea" + workArea.toString(), workArea);
            CardLayout cardLayout = (CardLayout) mainJFrame.getContentPane().getLayout();
            cardLayout.next(mainJFrame.getContentPane());
        } else if ("Marketing".equals(role)) {
            ui.marketing.WorkArea workArea = new ui.marketing.WorkArea(mainJFrame.getContentPane(), business, userAccount);
            mainJFrame.getContentPane().add("MarketingWorkArea" + workArea.toString(), workArea);
            CardLayout cardLayout = (CardLayout) mainJFrame.getContentPane().getLayout();
            cardLayout.next(mainJFrame.getContentPane());
        } else if ("Sales".equals(role)) {
            ui.sales.WorkArea workArea = new ui.sales.WorkArea(mainJFrame.getContentPane(), business, userAccount);
            mainJFrame.getContentPane().add("SalesWorkArea" + workArea.toString(), workArea);
            CardLayout cardLayout = (CardLayout) mainJFrame.getContentPane().getLayout();
            cardLayout.next(mainJFrame.getContentPane());
        } else if ("Customer".equals(role)) {
            ui.customer.WorkArea workArea = new ui.customer.WorkArea(mainJFrame.getContentPane(), business, userAccount);
            mainJFrame.getContentPane().add("CustomerWorkArea" + workArea.toString(), workArea);
            CardLayout cardLayout = (CardLayout) mainJFrame.getContentPane().getLayout();
            cardLayout.next(mainJFrame.getContentPane());
        } else {
            JOptionPane.showMessageDialog(this, "Unrichable code.", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("[Error] Unrichable code executed [Class: LoginScreen, Method: btnLoginActionPerformed]");
        }
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
